export const GET_GALLERY = "GET_GALLERY";
export const GET_SINGLE_GALLERY = "GET_SINGLE_GALLERY";
export const ADD_GALLERY = "ADD_GALLERY";
export const UPDATE_GALLERY = "UPDATE_GALLERY";
export const DELETE_GALLERY = "DELETE_GALLERY";
