export const GET_PACKAGE = "GET_PACKAGE";
export const ADD_PACKAGE = "ADD_PACKAGE";
export const UPDATE_PACKAGE = "UPDATE_PACKAGE";
export const DELETE_PACKAGE = "DELETE_PACKAGE";

export const GET_PACKAGE_ORDERS = "GET_PACKAGE_ORDERS";
export const CONFIRM_PACKAGE_ORDERS = "CONFIRM_PACKAGE_ORDERS";
